INTERVAL_BED_FILE=$RDIR/assets/Targets/Twist_Mouse_Exome_Target_Rev1_GRCm38/Twist_Mouse_Exome_Target_Rev1_7APR20_GRCm38_CLEAN__1000pad.bed
BAIT_INTERVALS=$RDIR/assets/Targets/Twist_Mouse_Exome_Target_Rev1_GRCm38/Twist_Mouse_Exome_Target_Rev1_7APR20_GRCm38_baits.ilist
TARGET_INTERVALS=$RDIR/assets/Targets/Twist_Mouse_Exome_Target_Rev1_GRCm38/Twist_Mouse_Exome_Target_Rev1_7APR20_GRCm38_targets.ilist
